pub mod health;

// Route modules that depend on service facade implementations.
// These are gated during development while the facades are being finalized.
#[cfg(feature = "full-api")]
pub mod site;
#[cfg(feature = "full-api")]
pub mod about;
#[cfg(feature = "full-api")]
pub mod session;
#[cfg(feature = "full-api")]
pub mod users;
#[cfg(feature = "full-api")]
pub mod topics;
#[cfg(feature = "full-api")]
pub mod posts;
#[cfg(feature = "full-api")]
pub mod post_actions;
#[cfg(feature = "full-api")]
pub mod categories;
#[cfg(feature = "full-api")]
pub mod groups;
#[cfg(feature = "full-api")]
pub mod tags;
#[cfg(feature = "full-api")]
pub mod search;
#[cfg(feature = "full-api")]
pub mod notifications;
#[cfg(feature = "full-api")]
pub mod bookmarks;
#[cfg(feature = "full-api")]
pub mod drafts;
#[cfg(feature = "full-api")]
pub mod uploads;
#[cfg(feature = "full-api")]
pub mod badges;
#[cfg(feature = "full-api")]
pub mod invites;
#[cfg(feature = "full-api")]
pub mod polls;
#[cfg(feature = "full-api")]
pub mod directory;
#[cfg(feature = "full-api")]
pub mod review;
#[cfg(feature = "full-api")]
pub mod websocket_handler;
#[cfg(feature = "full-api")]
pub mod chat;
#[cfg(feature = "full-api")]
pub mod admin;
